#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Restaurant_Android.Resource", IsApplication=true)]

namespace Restaurant_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bb1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bb2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cart = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cart2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chk1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ck1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cn1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int conn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cuser = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int def = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dis = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int discon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int done1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int download1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int eh1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ek1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int f1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int h1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int hh1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int home = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon4 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ip1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int k1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int login = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int logo1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int menu1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int menu2 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int menu3 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int menu4 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int mmenu = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int n1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int none1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ph1 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int plus = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int pn1 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int print = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int r1 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int res4 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int res5 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int save1 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int save2 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int silk_route = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int sync = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int update1 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int upload1 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int vn1 = 2130837555;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050072
			public const int bnttest1 = 2131034226;
			
			// aapt resource value: 0x7f05001f
			public const int btnahome1 = 2131034143;
			
			// aapt resource value: 0x7f05004f
			public const int btnback1 = 2131034191;
			
			// aapt resource value: 0x7f050053
			public const int btnback2 = 2131034195;
			
			// aapt resource value: 0x7f050057
			public const int btnback3 = 2131034199;
			
			// aapt resource value: 0x7f05005b
			public const int btnback4 = 2131034203;
			
			// aapt resource value: 0x7f050076
			public const int btnback5 = 2131034230;
			
			// aapt resource value: 0x7f050038
			public const int btnbin6 = 2131034168;
			
			// aapt resource value: 0x7f050047
			public const int btnbin7 = 2131034183;
			
			// aapt resource value: 0x7f050051
			public const int btncart1 = 2131034193;
			
			// aapt resource value: 0x7f050055
			public const int btncart2 = 2131034197;
			
			// aapt resource value: 0x7f050059
			public const int btncart3 = 2131034201;
			
			// aapt resource value: 0x7f05005d
			public const int btncart4 = 2131034205;
			
			// aapt resource value: 0x7f050078
			public const int btncart5 = 2131034232;
			
			// aapt resource value: 0x7f050001
			public const int btncback1 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int btncback2 = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int btncback3 = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int btncback4 = 2131034134;
			
			// aapt resource value: 0x7f05002b
			public const int btncheck = 2131034155;
			
			// aapt resource value: 0x7f050002
			public const int btnchome1 = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int btnchome2 = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int btnchome3 = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int btnchome4 = 2131034135;
			
			// aapt resource value: 0x7f050025
			public const int btncreate = 2131034149;
			
			// aapt resource value: 0x7f050003
			public const int btncsave1 = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int btncsave2 = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int btncsave3 = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int btncsave4 = 2131034136;
			
			// aapt resource value: 0x7f05002c
			public const int btndiscon = 2131034156;
			
			// aapt resource value: 0x7f050050
			public const int btnhome1 = 2131034192;
			
			// aapt resource value: 0x7f050054
			public const int btnhome2 = 2131034196;
			
			// aapt resource value: 0x7f050058
			public const int btnhome3 = 2131034200;
			
			// aapt resource value: 0x7f05005c
			public const int btnhome4 = 2131034204;
			
			// aapt resource value: 0x7f050077
			public const int btnhome5 = 2131034231;
			
			// aapt resource value: 0x7f050037
			public const int btnhome6 = 2131034167;
			
			// aapt resource value: 0x7f050046
			public const int btnhome7 = 2131034182;
			
			// aapt resource value: 0x7f05002d
			public const int btnl1 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int btnl2 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int btnl3 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int btnl4 = 2131034160;
			
			// aapt resource value: 0x7f05006b
			public const int btnlog1 = 2131034219;
			
			// aapt resource value: 0x7f050071
			public const int btnlogin = 2131034225;
			
			// aapt resource value: 0x7f050021
			public const int btnlr1 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int btnlr2 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int btnlr3 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int btnlr4 = 2131034148;
			
			// aapt resource value: 0x7f050032
			public const int btnlre1 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int btnlre2 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int btnlre3 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int btnlre4 = 2131034165;
			
			// aapt resource value: 0x7f050082
			public const int btnorder = 2131034242;
			
			// aapt resource value: 0x7f050036
			public const int btnprint6 = 2131034166;
			
			// aapt resource value: 0x7f050075
			public const int btnregister = 2131034229;
			
			// aapt resource value: 0x7f050085
			public const int btnri1 = 2131034245;
			
			// aapt resource value: 0x7f050089
			public const int btnri2 = 2131034249;
			
			// aapt resource value: 0x7f05008d
			public const int btnri3 = 2131034253;
			
			// aapt resource value: 0x7f050091
			public const int btnri4 = 2131034257;
			
			// aapt resource value: 0x7f050087
			public const int btnribin1 = 2131034247;
			
			// aapt resource value: 0x7f05008b
			public const int btnribin2 = 2131034251;
			
			// aapt resource value: 0x7f05008f
			public const int btnribin3 = 2131034255;
			
			// aapt resource value: 0x7f050093
			public const int btnribin4 = 2131034259;
			
			// aapt resource value: 0x7f050086
			public const int btnrihome1 = 2131034246;
			
			// aapt resource value: 0x7f05008a
			public const int btnrihome2 = 2131034250;
			
			// aapt resource value: 0x7f05008e
			public const int btnrihome3 = 2131034254;
			
			// aapt resource value: 0x7f050092
			public const int btnrihome4 = 2131034258;
			
			// aapt resource value: 0x7f050045
			public const int btnsave7 = 2131034181;
			
			// aapt resource value: 0x7f05002a
			public const int btnsetip = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int btnsync1 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int btnsync2 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btnsync3 = 2131034152;
			
			// aapt resource value: 0x7f050070
			public const int btnview = 2131034224;
			
			// aapt resource value: 0x7f050040
			public const int cartgrid1 = 2131034176;
			
			// aapt resource value: 0x7f050080
			public const int ccno1 = 2131034240;
			
			// aapt resource value: 0x7f05004d
			public const int cno2 = 2131034189;
			
			// aapt resource value: 0x7f050073
			public const int editText3 = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int editText4 = 2131034228;
			
			// aapt resource value: 0x7f05003d
			public const int empid = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int emppw = 2131034174;
			
			// aapt resource value: 0x7f050052
			public const int gridView1 = 2131034194;
			
			// aapt resource value: 0x7f050056
			public const int gridView2 = 2131034198;
			
			// aapt resource value: 0x7f05005a
			public const int gridView3 = 2131034202;
			
			// aapt resource value: 0x7f05005e
			public const int gridView4 = 2131034206;
			
			// aapt resource value: 0x7f05006f
			public const int imageView1 = 2131034223;
			
			// aapt resource value: 0x7f05005f
			public const int imgBtn1 = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int imgBtn11 = 2131034209;
			
			// aapt resource value: 0x7f050063
			public const int imgBtn3 = 2131034211;
			
			// aapt resource value: 0x7f050065
			public const int imgBtn4 = 2131034213;
			
			// aapt resource value: 0x7f050067
			public const int imgBtn5 = 2131034215;
			
			// aapt resource value: 0x7f050041
			public const int imgBtn6 = 2131034177;
			
			// aapt resource value: 0x7f050079
			public const int imgm1 = 2131034233;
			
			// aapt resource value: 0x7f05001b
			public const int ldes4 = 2131034139;
			
			// aapt resource value: 0x7f050007
			public const int limg1 = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int limg2 = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int limg3 = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int limg4 = 2131034142;
			
			// aapt resource value: 0x7f050006
			public const int limgbtn1 = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int limgbtn2 = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int limgbtn3 = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int limgbtn4 = 2131034141;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050039
			public const int linearLayout2 = 2131034169;
			
			// aapt resource value: 0x7f05007d
			public const int linearLayout3 = 2131034237;
			
			// aapt resource value: 0x7f050083
			public const int llv1 = 2131034243;
			
			// aapt resource value: 0x7f050005
			public const int lname1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int lname2 = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int lname3 = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int lname4 = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int lp4 = 2131034140;
			
			// aapt resource value: 0x7f05006d
			public const int mylistView1 = 2131034221;
			
			// aapt resource value: 0x7f05006c
			public const int mylistView11 = 2131034220;
			
			// aapt resource value: 0x7f05006e
			public const int mylistView3 = 2131034222;
			
			// aapt resource value: 0x7f050084
			public const int print1 = 2131034244;
			
			// aapt resource value: 0x7f05003b
			public const int space1 = 2131034171;
			
			// aapt resource value: 0x7f05004b
			public const int space2 = 2131034187;
			
			// aapt resource value: 0x7f050048
			public const int space3 = 2131034184;
			
			// aapt resource value: 0x7f05000b
			public const int spinner1 = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int spinner3 = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int spinner4 = 2131034137;
			
			// aapt resource value: 0x7f050088
			public const int spr1 = 2131034248;
			
			// aapt resource value: 0x7f05008c
			public const int spr2 = 2131034252;
			
			// aapt resource value: 0x7f050090
			public const int spr3 = 2131034256;
			
			// aapt resource value: 0x7f050094
			public const int spr4 = 2131034260;
			
			// aapt resource value: 0x7f05007f
			public const int spsr1 = 2131034239;
			
			// aapt resource value: 0x7f05004c
			public const int spsr2 = 2131034188;
			
			// aapt resource value: 0x7f05003c
			public const int sptpos1 = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int tabno1 = 2131034170;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050031
			public const int textView2 = 2131034161;
			
			// aapt resource value: 0x7f050020
			public const int textView3 = 2131034144;
			
			// aapt resource value: 0x7f05004a
			public const int txtccount = 2131034186;
			
			// aapt resource value: 0x7f05004e
			public const int txtcdes1 = 2131034190;
			
			// aapt resource value: 0x7f050049
			public const int txtcid1 = 2131034185;
			
			// aapt resource value: 0x7f05007c
			public const int txtdes = 2131034236;
			
			// aapt resource value: 0x7f050029
			public const int txtip = 2131034153;
			
			// aapt resource value: 0x7f050060
			public const int txtname = 2131034208;
			
			// aapt resource value: 0x7f050062
			public const int txtname1 = 2131034210;
			
			// aapt resource value: 0x7f050064
			public const int txtname3 = 2131034212;
			
			// aapt resource value: 0x7f050066
			public const int txtname4 = 2131034214;
			
			// aapt resource value: 0x7f050068
			public const int txtname5 = 2131034216;
			
			// aapt resource value: 0x7f050042
			public const int txtname6 = 2131034178;
			
			// aapt resource value: 0x7f050044
			public const int txtname7 = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int txtname8 = 2131034179;
			
			// aapt resource value: 0x7f05007b
			public const int txtprice = 2131034235;
			
			// aapt resource value: 0x7f05006a
			public const int txtpwd1 = 2131034218;
			
			// aapt resource value: 0x7f05007e
			public const int txtqty = 2131034238;
			
			// aapt resource value: 0x7f050081
			public const int txtremark = 2131034241;
			
			// aapt resource value: 0x7f05007a
			public const int txttitle = 2131034234;
			
			// aapt resource value: 0x7f05003f
			public const int txttotal = 2131034175;
			
			// aapt resource value: 0x7f050069
			public const int txtun1 = 2131034217;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_level1_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int add_level2_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int add_level3_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int add_level4_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int admin1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int cartview1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int cartviewadapter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int edit_cart = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int layout1 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layout2 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int layout3 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int layout4 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int listview_row = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int listview_row1 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int listview_row3 = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int listview_row4 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int listview_row5 = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int login = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int lv1 = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int lv2 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int lv3 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Main = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Newuser = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int order1 = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int printview = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Remove_Level1_Item = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Remove_Level2_Item = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Remove_Level3_Item = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Remove_Level4_Item = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
